apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: foodgram
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
