apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media
      volumes:
        - name: collected-static-files
          persistentVolumeClaim:
            claimName: {{ .Values.global.persistence.collectedStatic.name }}
        - name: media-files
          persistentVolumeClaim:
            claimName: {{ .Values.global.persistence.media.name }}

