apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "foodgram-chart.labels" (dict "component" "frontend" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foodgram-chart.selectorLabels" (dict "component" "frontend" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foodgram-chart.selectorLabels" (dict "component" "frontend" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media
      volumes:
        - name: collected-static-files
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.collect-static.name }}
        - name: media-files
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.media.name }}
