image:
  repository: foodgram_backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: backend-service
  port: 8000

persistence:
  collectedStatic:
    enabled: true
  media:
    enabled: true

envVars:
  DJANGO_SECRET_KEY: "devsecret"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "*"

database:
  port: 5432

pvc:
  media:
    name: media-pvc
    accessModes: ReadWriteOnce
    storage: 1Gi
  collect-static:
    name: collected-static-pvc
    accessModes: ReadWriteOnce
    storage: 1Gi
