replicaCount: 1

image:
  repository: foodgram_backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: backend-service
  port: 8000

envVars:
  DJANGO_SECRET_KEY: "devsecret"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "*"

database:
  port: 5432

envFrom: []
 - configMapRef:
    name: redis-conn
 - secretRef:
    name: redis-auth

