replicaCount: 1

global:
  postgresql:
    auth:
      username: postgres
      password: postgres
      database: foodgram

image:
  repository: UiminaM/foodgram
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: backend-service
  port: 8000

autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 35
    targetMemoryUtilizationPercentage: 75
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 0
        selectPolicy: Max
        policies:
          - type: Percent
            value: 100
            periodSeconds: 60
          - type: Pods
            value: 2
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 60
        selectPolicy: Max
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
          - type: Pods
            value: 5
            periodSeconds: 60
  vpa:
    enabled: true
    updateMode: "Off"
    controlledResources:
      - cpu
      - memory
    minAllowed:
      cpu: 100m
      memory: 128Mi
    maxAllowed:
      cpu: "1"
      memory: 1Gi

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi

initResources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 64Mi

envVars:
  DJANGO_SECRET_KEY: "devsecret"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "*"

database:
  port: 5432

envFrom:
  - configMapRef:
      name: redis-conn
  - secretRef:
      name: redis-auth

