apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.port }}
    protocol: TCP
  type: ClusterIP
