apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.port }}
    protocol: TCP
  type: ClusterIP
