replicaCount: 1

image:
  repository: UiminaM/foodgram-frontend
  tag: "1.1.0"
  pullPolicy: IfNotPresent

service:
  name: frontend-service
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
