apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: {{ .Values.database.port | quote }}
  DJANGO_SECRET_KEY: {{ .Values.backend.envVars.DJANGO_SECRET_KEY | quote }}
  DJANGO_DEBUG: {{ .Values.backend.envVars.DJANGO_DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.backend.envVars.ALLOWED_HOSTS | quote }}

