apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ .Release.Name }}-postgresql {{ .Values.database.port }}; do
                echo "Waiting for database..."
                sleep 2
              done
        - name: collect-static
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - configMapRef:
                name: backend-configmap
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media

      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: backend-configmap
            {{- if .Values.envFrom }}
            {{- range .Values.envFrom }}
            - {{ . | toYaml | nindent 14 }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media

      volumes:
        - name: collected-static-files
          persistentVolumeClaim:
            claimName: {{ .Values.global.persistence.collectedStatic.name }}
        - name: media-files
          persistentVolumeClaim:
            claimName: {{ .Values.global.persistence.media.name }}

