apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "foodgram-chart.labels" (dict "component" "backend" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foodgram-chart.selectorLabels" (dict "component" "backend" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foodgram-chart.selectorLabels" (dict "component" "backend" "context" .) | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ .Release.Name }}-postgresql {{ .Values.database.port }}; do
                echo "Waiting for database..."
                sleep 2
              done
        - name: collect-static
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - configMapRef:
                name: backend-configmap
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media

      containers:
        - name: backend
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-configmap
          volumeMounts:
            - name: collected-static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media

      volumes:
        - name: collected-static-files
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.collect-static.name }}
        - name: media-files
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.media.name }}