apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.media.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.media.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.media.storage }}