locustfile = load_tests/locustfile.py
host = http://127.0.0.1:8000
users = 300
spawn-rate = 30
run-time = 8m
headless = true
html = load_tests/reports/foodgram-report.html
csv = load_tests/reports/foodgram
